version: '3.8'

services:
  web:
    build: ./services/web
    # command: python run -h 0.0.0.0
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 8000:5000
    env_file:
      - ./.env